### ISSUE TITLE
Visual glitch when moving window offscreen

### ISSUE THREAD

**Issue by pitothepowerof3** [PAT457/Reality#9]
![image of glitch](http://i.imgur.com/re9lhiz.png)

When you move the window off screen, then drag it back, it causes the glitch seen above.

**Comment by PAT457** [comment]
I'm pretty sure that can't be fixed. I know that bug, but its just monogame. It can't be fixed but I might try some brute force ways.

**Comment by ghost** [comment]
This should be closed
